spring.application.name=cinemate

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/cinemate_db
spring.datasource.username=admin
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration
jwt.signer-key=S7RxfF0UMgBdOAfHdDjklZm7lF3rTLjqWNrDgcXsNqm8Yw3KeVf9aHbPnYcXzJhQ
jwt.expiration=3600
jwt.reset-token-expiration=900

# Mail Configuration (SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=contact.basaucycle2026@gmail.com
spring.mail.password=pjtimradspubfhcg
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


#Cloudinary Configuration
cloudinary.cloud-name=dod2rhslh
cloudinary.api-key=452779535846727
cloudinary.api-secret=hf1c5E8DyC2lwEUuPuxQyg1NyhU